In [2]:
!pip install tensorflow


In [6]:
import tensorflow as tf

In [8]:
tf.constant([

           [[0, 1, 2, 3, 4],

            [5, 6, 7, 8, 9]],

           [[10, 11, 12, 13, 14],

            [15, 16, 17, 18, 19]],

           [[20, 21, 22, 23, 24],

            [25, 26, 27, 28, 29]],])

<tf.Tensor: shape=(3, 2, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])>

In [46]:
tf.constant([[1, 2],
[3, 4],

[5, 6]], dtype=tf.float16)

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [51]:
tf.constant([

           [[0, 1, 2, 3, 4],

            [5, 6, 7, 8, 9]],

           [[10, 11, 12, 13, 14],

            [15, 16, 17, 18, 19]],

           [[20, 21, 22, 23, 24],

            [25, 26, 27, 28, 29]],])

<tf.Tensor: shape=(3, 2, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])>

In [48]:
tf.shape

<function tensorflow.python.ops.array_ops.shape_v2(input, out_type=tf.int32, name=None)>

In [24]:
tensor = tf.constant([2, 14, 10, 12, 15, 3, 2, 5, 15, 78])

In [25]:
tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [26]:
tensor[-1]

<tf.Tensor: shape=(), dtype=int32, numpy=78>

In [27]:
tensor[:5]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 2, 14, 10, 12, 15])>

In [29]:
tensor[0::2]


<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 2, 10, 15,  2, 15])>

In [30]:
t = [

[3, 2, 1],

[6, 5, 4],

[9, 8, 7]

]

In [31]:
t[1][0]

6

In [32]:
t = tf.constant([

    [

         [2, 4, 4, 3] 

        ,[3, 2, 4, 5]

    ]

])

In [33]:
t.shape

TensorShape([1, 2, 4])

In [45]:
tf.constant([[1, 2],
[3, 4],

[5, 6]], dtype=tf.float16)

 

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [24]:
t = tf.constant([9, 10, 11, 12])
t.ndim

1